# Generated by Django 3.0.7 on 2020-06-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cat', models.CharField(max_length=150, unique=True, verbose_name='Categoria')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salario Liquido')),
                ('valor_extra', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Extra')),
                ('data_sal', models.DateTimeField()),
                ('data_extra', models.DateTimeField()),
            ],
            options={
                'db_table': 'salario',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_desp', models.CharField(max_length=150, verbose_name='Descrição da Despesa')),
                ('valor_dep', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Despesa')),
                ('data_dep', models.DateTimeField()),
                ('data_reg_dep', models.DateTimeField(auto_now=True)),
                ('cat_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fin.Categoria', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
    ]
