# Generated by Django 3.0.7 on 2020-06-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0004_meses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meses',
            table='meses',
        ),
    ]
