# Generated by Django 3.0.7 on 2020-06-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0005_auto_20200623_0204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meses',
        ),
    ]
